services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm run dev:watch
    environment:
      - NODE_ENV=development
      - PORT=8080
      - CI=true
      - CHOKIDAR_USEPOLLING=true

  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: pnpm run dev -- --host
    environment:
      - VITE_API_URL=http://localhost:8080
      - CI=true
      - CHOKIDAR_USEPOLLING=true
